# Generated by Django 3.0 on 2020-07-25 10:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('student_email', models.CharField(max_length=200)),
                ('student_timeofreg', models.DateTimeField(default=datetime.datetime.now, verbose_name='time of registration')),
            ],
        ),
    ]
