# Generated by Django 3.0 on 2020-07-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_timeofreg',
        ),
    ]
