# Generated by Django 3.0 on 2020-07-25 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
