# Generated by Django 3.0 on 2020-07-25 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=200),
        ),
    ]
