# Generated by Django 3.0 on 2020-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200726_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(),
        ),
    ]
