# Generated by Django 3.0 on 2020-07-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_student_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, upload_to='student_img/'),
        ),
    ]
