# Generated by Django 3.0 on 2020-07-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200726_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
