# Generated by Django 3.0 on 2020-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200726_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
