# Generated by Django 3.0 on 2020-07-26 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200726_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_DOB',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
