# Generated by Django 3.0 on 2020-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, default='default/blank_user.png', upload_to='images/'),
        ),
    ]
