# Generated by Django 3.0 on 2020-07-26 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200726_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
