# Generated by Django 3.0 on 2020-07-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200727_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, default='default/blank_user.png', upload_to='images/', verbose_name='Upload an image of the student'),
        ),
    ]
