# Generated by Django 3.0 on 2020-07-27 04:56

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200727_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_DOB',
            field=models.DateField(default=datetime.datetime.now, validators=[main.models.no_Future_Dob], verbose_name='Enter Date of Birth of Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, validators=[main.models.checkForDigits]),
        ),
    ]
