# Generated by Django 3.0 on 2020-07-27 05:09

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200727_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_DOB',
            field=models.DateField(default=datetime.datetime.now, help_text='Use the button on the right or the arrow keys to edit the date in DD-MM-YYYY format', validators=[main.models.no_Future_Dob], verbose_name='Enter Date of Birth of Student'),
        ),
    ]
