# Generated by Django 3.0 on 2020-07-28 06:50

import datetime
import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200727_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_marks_A',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_DOB',
            field=models.DateField(default=datetime.datetime.now, help_text='Use the button on the right or the arrow keys to edit the date', validators=[main.models.no_Future_Dob], verbose_name='Enter Date of Birth of Student in DD-MM-YYYY format'),
        ),
    ]
