# Generated by Django 3.0 on 2020-07-30 07:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200728_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_mobile_number',
            field=models.CharField(default=999999999, max_length=10, validators=[main.models.checkForAlpha]),
            preserve_default=False,
        ),
    ]
