# Generated by Django 3.0 on 2020-07-30 12:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_student_student_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_First_Name',
            field=models.TextField(default='Random', validators=[main.models.checkForDigits]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_Last_Name',
            field=models.TextField(default='Random', validators=[main.models.checkForDigits]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.TextField(validators=[main.models.checkForDigits]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_name', 'student_mobile_number')},
        ),
    ]
