# Generated by Django 3.0 on 2020-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_student_student_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Unique_ID',
            field=models.CharField(help_text='Please save this number, this will be used to unique identify the student', max_length=10),
        ),
    ]
