# Generated by Django 3.0 on 2020-07-30 15:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200730_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Unique_ID',
            field=models.CharField(default=main.models.get_random, help_text='Please save this number, this will be used to unique identify the student', max_length=10),
        ),
    ]
