# Generated by Django 3.0 on 2020-08-02 14:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200730_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField(validators=[main.models.checkForDigits])),
                ('Last_Name', models.TextField(validators=[main.models.checkForDigits])),
                ('Mobile_number', models.CharField(max_length=10, validators=[main.models.checkForAlpha])),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Unique_ID',
            field=models.CharField(default=main.models.get_random, help_text='Please save this number, this will be used to unique identify the student', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('guardian_mobile_number', 'student_First_Name', 'student_Last_Name')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
    ]
